# Generated by Django 4.1.2 on 2022-12-19 12:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='death_time',
            field=models.DecimalField(decimal_places=3, default=Decimal('1672059092206.010009765625'), max_digits=20, verbose_name='Time of Death for the message.'),
        ),
        migrations.AlterField(
            model_name='message',
            name='post_time',
            field=models.DecimalField(decimal_places=3, default=Decimal('1671454292206.010009765625'), max_digits=20, verbose_name='Time of Death for the message.'),
        ),
    ]
