# Generated by Django 4.1.2 on 2022-12-19 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_message_death_time_alter_message_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='death_time',
            field=models.DecimalField(decimal_places=3, default=Decimal('1672059253582.905029296875'), max_digits=20, verbose_name='Time of Death for the message.'),
        ),
        migrations.AlterField(
            model_name='message',
            name='post_time',
            field=models.DecimalField(decimal_places=3, default=Decimal('1671454453582.905029296875'), max_digits=20, verbose_name='Time of Death for the message.'),
        ),
    ]
