# Generated by Django 4.1.2 on 2022-12-19 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_message_death_time_alter_message_post_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['post_date', 'author'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='death_time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='post_time',
        ),
        migrations.AddField(
            model_name='message',
            name='death_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 19, 22, 29, 24, 565550), verbose_name='Time of Death for the message.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 19, 22, 30, 4, 618182), verbose_name='The date of the message when it was posted.'),
            preserve_default=False,
        ),
    ]
